# Generated by Django 4.1.5 on 2023-01-27 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('shortened_link', models.URLField(blank=True, null=True)),
                ('custom_string', models.CharField(max_length=15)),
                ('click_count', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 13, 51, 50, 814667, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
