# Generated by Django 4.1.5 on 2023-01-27 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 13, 52, 15, 910156, tzinfo=datetime.timezone.utc)),
        ),
    ]
