# Generated by Django 4.1.5 on 2023-01-26 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 18, 52, 51, 352087)),
        ),
    ]
