# Generated by Django 4.1.5 on 2023-01-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_user_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
