# Generated by Django 4.1.5 on 2023-02-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_link_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 15, 55, 21, 708953, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.URLField(max_length=500),
        ),
    ]
