# Generated by Django 4.1.5 on 2023-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
